import '@radix-ui/themes/styles.css';
import './theme-config.css'


import NavBar from './NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="cyan"
              grayColor="gray"
              panelBackground="solid"
              scaling="100%"
              radius="large"  >
              <NavBar />
              <main className=' p-6'>
                {children}
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>

      </body>
    </html>
  )
}
