import '@radix-ui/themes/styles.css';
import './theme-config.css'


import NavBar from './NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.variable}>
        <AuthProvider>
            <Theme  appearance='light' accentColor='amber'  >
          <NavBar />
          <main className=' p-6'>
           <Container> {children}</Container>
          </main>
        </Theme>
        </AuthProvider>
      
      </body>
    </html>
  )
}
